# Generated by Django 4.2.30 on 2026-07-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_phoneverification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phoneverification',
            name='created_at',
        ),
        migrations.AddField(
            model_name='phoneverification',
            name='otp_created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
