# Generated by Django 4.2.30 on 2026-07-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_phoneverification_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneverification',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
