version: '3.9'

services:
  db:
    container_name: db
    image: docker.arvancloud.ir/postgres:15-alpine
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - 5432
    ports:
      - 5432:5432
    restart: always

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./dockerfiles/dev/django/Dockerfile
    volumes:
      - ./backend:/usr/src/app
    working_dir: /usr/src/app
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8888:8000
    environment:
      - DEBUG=True
    env_file:
      - ./envs/dev/django/.env
    restart: always
    depends_on:
      - db

  frontend:
    container_name: frontend

    build:
      context: .
      dockerfile: ./dockerfiles/dev/next/Dockerfile

    working_dir: /usr/src/app

    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules

    ports:
      - "3000:3000"

    command: npm run dev -- --hostname 0.0.0.0 --webpack

    env_file:
      - ./envs/dev/next/.env

    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true

    stdin_open: true
    tty: true

    restart: always

    depends_on:
      - backend

  smtp4dev:
    image: docker.arvancloud.ir/rnwood/smtp4dev:v3
    restart: always
    ports:
      - '5000:80'
      - '25:25'
      - '143:143'
    volumes:
      - smtp4dev-data:/smtp4dev
    environment:
      - serverOptions__HostName=smtp4dev

volumes:
  smtp4dev-data:

    
